use crate::json_struct::{Base16, Colors, MatugenTheme, OkShell, Palettes, color};

pub fn nightfox(okshell: OkShell) -> MatugenTheme {
    MatugenTheme {
        okshell,
        image: String::new(),
        is_dark_mode: true,
        mode: "dark".to_string(),
        base16: Base16 {
            base00: color("#192330"),
            base01: color("#212e3f"),
            base02: color("#29394f"),
            base03: color("#738091"),
            base04: color("#71839b"),
            base05: color("#cdcecf"),
            base06: color("#d6d6d7"),
            base07: color("#dfdfe0"),
            base08: color("#c94f6d"),
            base09: color("#f4a261"),
            base0a: color("#dbc074"),
            base0b: color("#81b29a"),
            base0c: color("#63cdcf"),
            base0d: color("#719cd6"),
            base0e: color("#9d79d6"),
            base0f: color("#d67ad2"),
        },
        palettes: Palettes::default(),
        colors: Colors {
            surface: color("#192330"),
            on_surface: color("#cdcecf"),
            surface_variant: color("#212e3f"),
            on_surface_variant: color("#aeafb0"),
            surface_container_highest: color("#39506d"),
            surface_container_high: color("#29394f"),
            surface_container: color("#212e3f"),
            surface_container_low: color("#192330"),
            surface_container_lowest: color("#131a24"),
            inverse_surface: color("#cdcecf"),
            inverse_on_surface: color("#192330"),
            surface_tint: color("#719cd6"),
            primary: color("#719cd6"),
            on_primary: color("#131a24"),
            primary_container: color("#2b3b51"),
            on_primary_container: color("#719cd6"),
            secondary: color("#9d79d6"),
            on_secondary: color("#131a24"),
            secondary_container: color("#2b3b51"),
            on_secondary_container: color("#9d79d6"),
            tertiary: color("#63cdcf"),
            on_tertiary: color("#131a24"),
            tertiary_container: color("#2b3b51"),
            on_tertiary_container: color("#63cdcf"),
            error: color("#c94f6d"),
            on_error: color("#131a24"),
            error_container: color("#2b3b51"),
            on_error_container: color("#c94f6d"),
            outline: color("#39506d"),
            outline_variant: color("#29394f"),
            background: color("#192330"),
            on_background: color("#cdcecf"),
            inverse_primary: color("#719cd6"),
            primary_fixed: color("#719cd6"),
            primary_fixed_dim: color("#7fb1f1"),
            on_primary_fixed: color("#131a24"),
            on_primary_fixed_variant: color("#cdcecf"),
            secondary_fixed: color("#9d79d6"),
            secondary_fixed_dim: color("#b48bf5"),
            on_secondary_fixed: color("#131a24"),
            on_secondary_fixed_variant: color("#cdcecf"),
            tertiary_fixed: color("#63cdcf"),
            tertiary_fixed_dim: color("#72ebed"),
            on_tertiary_fixed: color("#131a24"),
            on_tertiary_fixed_variant: color("#cdcecf"),
            scrim: color("#131a24"),
            shadow: color("#131a24"),
            source_color: color("#719cd6"),
            surface_bright: color("#3c5372"),
            surface_dim: color("#131a24"),
        },
    }
}
